### ISSUE TITLE
协程池

### ISSUE THREAD

**Issue by xuyang404** [sohaha/zlsgo-app#2]
大佬，请问有没有意向添加协程池以复用协程？因为有些并发很大的数据要处理的话，没有协程池会导致开很多协程，业务结束后又销毁，以往反复开销就会增大

**Comment by sohaha** [comment]
Goroutine Pool 池还是比较容易的呀，你也可以写一个 😆 PR 下。(我晚点抽空写一个

**Comment by xuyang404** [comment]
> Goroutine Pool 池还是比较容易的呀，你也可以写一个 😆 PR 下。(我晚点抽空写一个

技术不够，现在用的是之前在网上看的教程，但是比较简陋😂

**Comment by xuyang404** [comment]
MaxLifetime        
MaxOpenConns       
MaxIdleConns
请问一下上面这三个参数应该在gorm哪里使用呢？

**Comment by xuyang404** [comment]
sqlDB.SetMaxOpenConns(DatabaseConf().MaxOpenConns)这样用对吗？

**Comment by sohaha** [comment]
> sqlDB.SetMaxOpenConns(DatabaseConf().MaxOpenConns)这样用对吗？

正确

**Comment by sohaha** [comment]
@xuyang404 添加了

**Comment by xuyang404** [comment]
> @xuyang404 池的使用参考手册

好的，谢谢大佬

**Comment by xuyang404** [comment]
> @xuyang404 池的使用参考手册

如果是在协程中发生panic，那么PanicHandler是无法捕获的是吗？

**Comment by sohaha** [comment]
除非有其它地方捕获了，不然 PanicHandler 是一定会捕获(你设置了PanicHandler)

**Comment by xuyang404** [comment]
> 除非有其它地方捕获了，不然 PanicHandler 是一定会捕获(你设置了PanicHandler)

其他地方没有捕获，我在协程里面用zutil.CheckErr(err)，但是真正发生panic的时候，却并没有进入PanicHandler，如果不是在协程里发生panic就能进PanicHandler

**Comment by sohaha** [comment]
忘了写协程的 PanicHandler 😂  ，晚点加下

**Comment by xuyang404** [comment]
> 忘了写协程的 PanicHandler 😂 ，晚点加下

好的，感谢大佬

**Comment by xuyang404** [comment]
> @xuyang404 池的使用参考手册

请问协程池的使用手册在哪里呢？我在文档好像并没有找到

**Comment by sohaha** [comment]
已追加了捕获 panic 的设置

文档: 应用池 https://docs.73zls.com/zls-go/#/41ea56d8-f1d5-41d1-9de8-f13e5611beb4

可能你那边文档有本地缓存,多刷新一下试试

**Comment by xuyang404** [comment]
> 已追加了捕获 panic 的设置

全局异常处理好像还是无法捕获协程中的panic

**Comment by sohaha** [comment]
两者又不在同一个时空呀。

所以捕获到 panic 之后要自行处理。

你应该思考为什么代码会出现 panic 并且解决它。

**Comment by xuyang404** [comment]
> 两者又不在同一个时空呀。
> 
> 所以捕获到 panic 之后要自行处理。
> 
> 你应该思考为什么代码会出现 panic 并且解决它。

我目前的做法是传个channel进去收集err，然后返回客户端，好知道发生了什么

**Comment by sohaha** [comment]
error 和 panic 是两种东西了，

如果想其中一个发生 err 就不使用的话直接关闭池就算了，

但是 panic 是不应该发生的才对，除非代码没写好

**Comment by xuyang404** [comment]
> error 和 panic 是两种东西了，
> 
> 如果想其中一个发生 err 就不使用的话直接关闭池就算了，
> 
> 但是 panic 是不应该发生的才对，除非代码没写好

关闭池是整个池都关闭了还是只关闭当前的goroutine？

**Comment by sohaha** [comment]
整个,

一个 goroutine 发生了 err 直接 return 中断 goroutine 后面的执行就算了，

池的运行一般不需要人为去干扰

**Comment by xuyang404** [comment]
> 池的运行一般不需要人为去干扰

好的

**Comment by xuyang404** [comment]
type Form struct {
    Name string `json:"name"`
  }

  var data Form 

  c.Bind(&data)

请问上面的代码中，var data Form 和var *data Form 会有什么不同的效果吗？

**Comment by sohaha** [comment]
panic  

不能传指针的指针

**Comment by xuyang404** [comment]
> panic
> 
> 不能传指针的指针

噢噢，再请问下zzz build 里的 --pack是什么意思呢？跟build又有什么区别呢？

**Comment by sohaha** [comment]
我一般使用 -P 算是语法糖,  编译的文件小一点

**Comment by xuyang404** [comment]
> 我一般使用 -P 算是语法糖, 编译的文件小一点

--os linux/arm64 能编译出arm的程序吗？

**Comment by sohaha** [comment]
可以

**Comment by xuyang404** [comment]
关于协程池请教一个问题：我new了一个协程池，最大协程数为100，当某次请求到来，需要用到协程的时候，池里已经产生了25个协程并且这25个协程中是有闲置的，那么这次请求是会从这25个协程中的闲置协程中挑一个来用，还是再开一个新的协程？

**Comment by sohaha** [comment]
复用
